### ISSUE TITLE
Error installing Chatterbot

### ISSUE THREAD

**Issue by lowyuehanelu** [pcyuen98/ChatterBot-master#2]
error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
      ----------------------------------------
  ERROR: Command errored out with exit status 1: 'c:\users\pc1\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\PC1\\AppData\\Local\\Temp\\pip-install-_oj1d9w2\\preshed_0d53b9a995034161a522151c46ef8f6e\\setup.py'"'"'; __file__='"'"'C:\\Users\\PC1\\AppData\\Local\\Temp\\pip-install-_oj1d9w2\\preshed_0d53b9a995034161a522151c46ef8f6e\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\PC1\AppData\Local\Temp\pip-record-7s1fcrv4\install-record.txt' --single-version-externally-managed --prefix 'C:\Users\PC1\AppData\Local\Temp\pip-build-env-tjugx6p2\overlay' --compile --install-headers 'C:\Users\PC1\AppData\Local\Temp\pip-build-env-tjugx6p2\overlay\Include\preshed' Check the logs for full command output.
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\pc1\appdata\local\programs\python\python39\python.exe' 'c:\users\pc1\appdata\local\programs\python\python39\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\PC1\AppData\Local\Temp\pip-build-env-tjugx6p2\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools 'wheel>0.32.0,<0.33.0' Cython 'cymem>=2.0.2,<2.1.0' 'preshed>=2.0.1,<2.1.0' 'murmurhash>=0.28.0,<1.1.0' 'thinc>=7.0.8,<7.1.0' Check the logs for full command output.

**Comment by pcyuen98** [comment]
Will check on that

**Comment by pcyuen98** [comment]
**Try below**
redo step 1 
https://github.com/pcyuen98/ChatterBot-master/blob/main/README.md

Reference
https://github.com/gunthercox/ChatterBot/issues/2095

**If above has error, do below and redo above
Please  download the below , install and restart windows.**
**1. Download n install** 
https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=Community&rel=16

**2. Download n install**
https://go.microsoft.com/fwlink/?LinkId=691126
